sonar.projectKey=CBX-Exam-System
sonar.projectName=CBX-Exam-System
sonar.sources=.
sonar.exclusions=\
**/node_modules/**,\
**/dist/**,\
**/build/**,\
**/vendor/**,\
**/public/**,\
**/test-results/**,\
**/templates/**,\
**/coverage/**,\
**/output/**,\
**/playwright-results/**,\
**/templates/**,\
